# tmux configuration for macOS. ~/.tmux.conf loads this file.

# iTerm2-specific overrides for better emoji/unicode support
set -ga terminal-overrides ',xterm-256color:RGB'
set -as terminal-features ',xterm-256color:clipboard'

# Map 'y' to copy the visible selection to the system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy" # Use "xclip -selection clipboard" for Linux
