# Use vi
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key ESCAPE copy-mode
bind-key y      copy-mode
#bind-key -t vi-copy 'v' begin-selection
#bind-key -t vi-copy 'y' copy-selection
bind-key p paste-buffer

# choose-tree
bind-key s choose-tree -s

# Default config
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Enable emoji and unicode support
set -gq allow-passthrough on
setw -gq utf8 on

# Switch command key to CTRL-J
unbind C-b
set -g prefix C-j

unbind-key \\ ; bind-key \\ split-window -h -c "#{pane_current_path}" # let's open pane with current directory with -c option
unbind-key - ; bind-key - split-window -v -c "#{pane_current_path}"

# Pane: Vim Style Movements
bind-key -r h select-pane -L              # go left
bind-key -r j select-pane -D              # go down
bind-key -r l select-pane -R              # go right
bind-key -r k select-pane -U              # go up

# Pane: Arrow Movements
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

# Pane: Movements
bind-key -r C-h select-pane -t :.+
bind-key -r C-j select-pane -t :.+

# To get things like open * working on Mac
#set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Bigger history
set -g history-limit 10000

# New windows/pane in $PWD
bind c new-window -c '#{pane_current_path}'

# Use mouse for switching (breaks cut-n-paste!)
#setw -g mode-mouse on
#set-option -g mouse-select-pane on
set -g mouse on

# Don't exit copy mode when dragging with mouse
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X stop-selection

# Reload tmux.conf
unbind-key C-r ; bind-key C-r source-file ~/.tmux.conf \; display-message "Configuration reloaded"

# Switch status left and right
set -g status-right "[#S]"
set -g status-right-length 10

set -g status-left-length 70
set -g status-left "#[fg=red]#h : "


# Load the part for this OS: ~/.tmux.darwin.conf or ~/.tmux.linux.conf
if-shell 'test "$(uname -s)" = Darwin' 'source-file ~/.tmux.darwin.conf' 'source-file ~/.tmux.linux.conf'
