""
"" awilmore.com
""

" Personal
"colorscheme koehler
set background=dark
" solarized options 
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
"colorscheme codeschool

set directory=~/tmp/vi_swap
set nopaste

" NERDTree
"autocmd vimenter * if !argc() | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
map <C-l> :NERDTreeFind<CR><C-W>w

" Buffer shortcuts
map <C-j> <C-W>=<C-W>w
map <C-k> <C-W>w<C-W>_

" Cut-n-Paste
vmap <C-C> "+y
nmap <C-V> "+gP
imap <C-V> <ESC><C-V>i
vmap <D-C> "+y
nmap <D-V> "+gP
imap <D-V> <ESC><D-V>i

" Cut-n-Paste on OSX
"vmap <C-c> y:call system("pbcopy", getreg("\""))<CR>
"nmap <C-v> :call setreg("\"",system("pbpaste"))<CR>p
"vnoremap <D-c> y:call system("pbcopy", getreg("\""))<CR>
"nnoremap <D-v> :call setreg("\"",system("pbpaste"))<CR>p

"" ==========================================================
"" FROM: http://vim.wikia.com/wiki/Example_vimrc

" URL: http://vim.wikia.com/wiki/Example_vimrc
" Authors: http://vim.wikia.com/wiki/Vim_on_Freenode
" Description: A minimal, but feature rich, example .vimrc. If you are a
"              newbie, basing your first .vimrc on this file is a good choice.
"              If you're a more advanced user, building your own .vimrc based
"              on this file is still a good idea.

"------------------------------------------------------------
" Features {{{1
"
" These options and commands enable some very useful features in Vim, that
" no user should have to live without.

" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
"filetype indent plugin on
filetype plugin indent on

" TODO: CHECK THIS ONE

" Enable syntax highlighting
syntax on


"------------------------------------------------------------
" Must have options {{{1
"
" These are highly recommended options.

" Vim with default settings does not allow easy switching between multiple files
" in the same editor window. Users can use multiple split windows or multiple
" tab pages to edit multiple files, but it is still best to enable an option to
" allow easier switching between files.
"
" One such option is the 'hidden' option, which allows you to re-use the same
" window and switch from an unsaved buffer without saving it first. Also allows
" you to keep an undo history for multiple files when re-using the same window
" in this way. Note that using persistent undo also lets you undo in multiple
" files even in the same window, but is less efficient and is actually designed
" for keeping undo history after closing Vim entirely. Vim will complain if you
" try to quit without saving, and swap files will keep you safe if your computer
" crashes.
"set hidden

" Note that not everyone likes working this way (with the hidden option).
" Alternatives include using tabs or split windows instead of re-using the same
" window as mentioned above, and/or either of the following options:
" set confirm
" set autowriteall

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch

" Modelines have historically been a source of security vulnerabilities. As
" such, it may be a good idea to disable them and use the securemodelines
" script, <http://www.vim.org/scripts/script.php?script_id=1876>.
" set nomodeline


"------------------------------------------------------------
" Usability options {{{1
"
" These are options that users frequently set in their .vimrc. Some of them
" change Vim's behaviour in ways which deviate from the true Vi way, but
" which are considered to add usability. Which, if any, of these options to
" use is very much a personal preference, but they are harmless.

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" Use visual bell instead of beeping when doing something wrong
set visualbell

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
set t_vb=

" Enable use of the mouse for all modes
set mouse=a

" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2

" Display line numbers on the left
set number

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" Use <F11> to toggle between 'paste' and 'nopaste'
"set pastetoggle=<F11>


"------------------------------------------------------------
" Indentation options {{{1
"
" Indentation settings according to personal preference.

" Indentation settings for using 2 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=2
set softtabstop=2
set expandtab

" Indentation settings for using hard tabs for indent. Display tabs as
" two characters wide.
"set shiftwidth=2
"set tabstop=2


"------------------------------------------------------------
" Mappings {{{1
"
" Useful mappings

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
"nnoremap <C-L> :nohl<CR><C-L>


"------------------------------------------------------------
" Autostart with NERDTree
"au VimEnter * NERDTree
"au VimEnter * wincmd l


"------------------------------------------------------------
" Puppet hacks
set modeline
set fo=tcq
au BufRead,BufNewFile *.pp set filetype=puppet

" Markdown hack
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd BufNewFile,BufRead *.md set filetype=markdown
"map <C-m> :! macdown %<CR><CR>

" Wrapping lines without breaking words
set wrap linebreak nolist

" Show whitespace
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

" AutoSave Plugin - map toggle to CTRL-SHIFT-S
map <C-S> :AutoSaveToggle<CR>

" Fix for crontab
autocmd filetype crontab setlocal nobackup nowritebackup

" JSON
" json_reformat is part of yajl: http://lloyd.github.com/yajl/
"autocmd FileType json set equalprg=json_reformat
"autocmd FileType json set equalprg=json_pp
autocmd FileType json set equalprg=jq\ .

" Don't hide quotes for JSON files
au FileType json set conceallevel=0

" Change dir to current file
"autocmd BufEnter * silent! lcd %:p:h

" Change NERDTree list to current file
"autocmd BufEnter * NERDTreeFind | wincmd w

" Start with NERDTree open
"autocmd VimEnter * NERDTree | wincmd w
"autocmd VimEnter * if !argc() | NERDTree | wincmd w | endif
"autocmd VimEnter * if !argc() | NERDTree | else | NERDTree | wincmd w | endif
autocmd VimEnter * if !argc() | NERDTree | elseif !&diff | NERDTree | wincmd w | NERDTreeFind | wincmd w | endif

" Close when NERDTree last window
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
  if exists("t:NERDTreeBufName")
    if bufwinnr(t:NERDTreeBufName) != -1
      if winnr("$") == 1
        q
      endif
    endif
  endif
endfunction



" CUSTOM
command CD execute "!cd %:p:h && echo ' *** SPAWNING NEW SHELL IN CURRENT DIRECTORY *** ' && echo && sleep 1 && bash"



""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""
"" EXPERIMENTAL: ESC REMAPING
""

"noremap `` <Esc>
"inoremap `` <Esc>
"nnoremap `` <Esc>
"vnoremap `` <Esc>
"onoremap `` <Esc>

""
"" EXPERIMENTAL: Python
""

autocmd FileType py setl sw=4 sts=4 expandtab tabstop=4 smarttab

""
"" EXPERIMENTAL: Golang
""

autocmd FileType go setl sw=4 sts=4 noexpandtab tabstop=4 smarttab

""
"" EXPERIMENTAL: Ack
""

" Options:
"noremap <Leader>a :Ack <cword><cr>
"vnoremap <Leader>a y:Ack <C-r>=fnameescape(@")<CR><CR>

"noremap <C-a> :NERDTreeClose<CR>:Ack<CR>
noremap <C-a> #:NERDTreeClose<CR>:Ack<CR>
noremap <C-q> :q<CR>


""
"" EXPERIMENTAL: Format shortcut
""
"noremap <S-f> :w<CR>ggVG=''
noremap <S-f> ggVG=''


""
"" EXPERIMENTAL: vsplits
""

noremap <C-]> :vertical resize +50<CR>
"noremap <C-[> :vertical resize -50<CR>  # this maps to escape as well for some reason




""
"" EXPERIMENTAL: Folding
""
"" Notes (via https://stackoverflow.com/questions/2362914/fold-function-in-vim)
""
"" zM closes all open folds
"" zR decreases the foldlevel to zero -- all folds will be open
"" zc closes a fold under cursor
"" zo opens a fold at the cursor
"" zO opens all folds at the cursor
"" zj moves the cursor to the next fold
"" zk moves the cursor to the previous fold
"" za toggle a fold at the cursor
"" zm increases the foldlevel by one
"" zr decreases the foldlevel by one
"" zd deletes the fold at the cursor
"" zE deletes all folds
"" [z move to start of open fold
"" ]z move to end of open fold

"jset foldmethod=indent
"set foldlevel=1
"set foldclose=all



""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

